version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=cfrunway
      - PGPASSWORD=postgres_password
      - PGPORT=5432git 
      - POSTGRES_PASSWORD=postgres_password
    # ports:
      # - "5432:5432"

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3060:80"
  
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=cfrunway
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - POSTGRES_PASSWORD=postgres_password
    depends_on:
     - postgres
    # ports:
      # - "5000:5000"
  
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    # ports:
      # - "3000:3000"