// action types

const actionType = {
  LOAD_PROJECT_CARDS: 'LOAD_PROJECT_CARDS',
  LOAD_PROJECT: 'LOAD_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  LOAD_FIN_DATA: 'LOAD_FIN_DATA',
  SELECT_FIN_DATA: 'SELECT_FIN_DATA',
  CLEAR_CUR_FIN_DATA: 'CLEAR_CUR_FIN_DATA',
  UPDATE_BARLINE_CHART: 'UPDATE_BARLINE_CHART',
  UPDATE_REV_DONUT_CHART: 'UPDATE_REV_DONUT_CHART',
  UPDATE_COST_DONUT_CHART: 'UPDATE_COST_DONUT_CHART',
};

export default actionType;
